In [ ]:
#Navie Bayes and SVC
#streamlit web app creation

In [ ]:
#count vectorizer 

In [27]:
str1=["hello and welcome to the intel program","hi and welcome to intel  unnati program"]
str1

['hello and welcome to the intel program',
 'hi and welcome to intel  unnati program']

In [28]:
str1[0]

'hello and welcome to the intel program'

In [29]:
str1[0].split()

['hello', 'and', 'welcome', 'to', 'the', 'intel', 'program']

In [30]:
str1[1].split()

['hi', 'and', 'welcome', 'to', 'intel', 'unnati', 'program']

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer(stop_words='english')

In [32]:
op=vect.fit_transform(str1).toarray()
op

array([[1, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 1]])

In [33]:
import pandas as pd
op1=pd.DataFrame(op,columns=vect.get_feature_names_out())
op1

hello  hi  intel  program  unnati  welcome
0      1   0      1        1       0        1
1      0   1      1        1       1        1

In [74]:
import pandas as pd
df=pd.read_csv('Iris.csv')
last_column = df.columns[-1]
df[last_column] = pd.Categorical(df[last_column]).codes
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [83]:
df.drop(columns=['Id'], inplace=True)

In [84]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [85]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [86]:
x = df.iloc[:, :-1].values
y = df.iloc[:, 4].values

#X = iris.iloc[:, :-1].values
#y = iris.iloc[:, 4].values

In [89]:
x.shape

(150, 4)

In [90]:
y.shape

(150,)

In [91]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [92]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [94]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=2)

In [95]:
from sklearn.naive_bayes import GaussianNB
model1=GaussianNB()

In [97]:
model1.fit(X_train,y_train)

GaussianNB()

In [99]:
model1.predict(X_test)

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1], dtype=int8)

In [35]:
#df.to_csv("spam.csv") #to save fdf file in csv format

In [12]:
x=df.iloc[:,1].values
y=df.iloc[:,0].values

In [37]:
x[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [38]:
x[1]

'Ok lar... Joking wif u oni...'

In [39]:
x[2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer(stop_words='english')

In [14]:
x_train_vect=vect.fit_transform(x_train)
x_test_vect=vect.transform(x_test)

AttributeError: 'numpy.float64' object has no attribute 'lower'

In [46]:
from sklearn.naive_bayes import MultinomialNB
model1=MultinomialNB()

In [47]:
model1.fit(x_train_vect,y_train)

MultinomialNB()

In [48]:
y_pred1 = model1.predict(x_test_vect)
y_pred1

array(['ham', 'spam', 'ham', ..., 'spam', 'ham', 'ham'], dtype='<U4')

In [51]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

0.9863603732950467

In [52]:
sample1=['win free tickets']
sample1=vect.transform(sample1)
model1.predict(sample1)

array(['spam'], dtype='<U4')

In [53]:
sample1=['hi jo']
sample1=vect.transform(sample1)
model1.predict(sample1)

array(['ham'], dtype='<U4')

In [54]:
# using NB pipeline
from sklearn.pipeline import make_pipeline
model2=make_pipeline(CountVectorizer(),MultinomialNB())
model2.fit(x_train,y_train)

Pipeline(steps=[('countvectorizer', CountVectorizer()),
                ('multinomialnb', MultinomialNB())])

In [57]:
str1=["hello and welcome to the intel program","free free free"]
model2.predict(str1)

array(['ham', 'spam'], dtype='<U4')

In [58]:
y_pred2 = model2.predict(x_test)
y_pred2

array(['ham', 'spam', 'ham', ..., 'spam', 'ham', 'ham'], dtype='<U4')

In [59]:
model2.predict(["free free free"])

array(['spam'], dtype='<U4')

In [60]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)

0.9885139985642498

In [61]:
#using svm for model building
from sklearn.svm import SVC
model3=SVC().fit(x_train_vect,y_train)

In [63]:
y_pred3=model3.predict(x_test_vect)
y_pred3

array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [64]:

op=vect.transform(['sweet home'])
model3.predict(op)

array(['ham'], dtype=object)

In [65]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred3)

0.9813352476669059

In [66]:
#using pipeline for SVM 
from sklearn.pipeline import make_pipeline
model4=make_pipeline(CountVectorizer(),SVC())
model4.fit(x_train,y_train)

Pipeline(steps=[('countvectorizer', CountVectorizer()), ('svc', SVC())])

In [67]:
y_pred4 = model4.predict(x_test)
y_pred4

array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [68]:
model4.predict(["free free free"])

array(['spam'], dtype=object)

In [69]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred4)

0.9834888729361091

In [ ]:
#from above 4 models only model 2 gives the best accuracy

In [ ]:
#model persistance -pickle and joblib
#(used to export model and use it some wr else)

In [70]:
import joblib

In [71]:
joblib.dump(model2,'spam_model') #save model as file

['spam_model']

In [73]:
import pickle
pickle.dump(model2,open('spam-model1.pkl','wb')) # create pickle fi